const C=[['cydney','Cydney','CY','#f3c93f'],['sterling','Sterling','ST','#c4c5db'],['ryan','Ryan','RY','#a98cff'],['gabi','Gabi','GA','#8ccdff'],['cooper','Cooper','CO','#ff8f70'],['kenly','Kenly','KE','#73e1c2'],['ashley','Ashley','AS','#ff9ccf']].map(x=>({id:x[0],name:x[1],in:x[2],a:x[3]}));
const R={common:['Common','C','#9da2b7'],uncommon:['Uncommon','U','#35d6c5'],rare:['Rare','R','#f3c93f'],legendary:['Legendary','L','#b178ff']};
const tags=['Kitchen','Writing','Yard Project','Garage Sale','Battle','Fishing','County Fair','Sourdough','Softball','Cones','Chaos','Domestic Order'];
const E={cydney:'Silent Judgment',sterling:'Scope Creep',ryan:'Rules Exploit',gabi:'Baked Goods Morale',cooper:'Wrong Quest Momentum',kenly:'Precision Strike',ashley:'Softball Cannon'};
let user=null,accounts=[],selected=null,img=null,authErr='',busy=false,timer=null;
let state={page:'collection',sel:'cydney',cards:[],tokens:Object.fromEntries(C.map(c=>[c.id,0])),prices:Object.fromEntries(C.map(c=>[c.id,1])),cash:0,draft:{cid:'cydney',title:'Cydney, Kitchen Authority',tag:'Kitchen',prev:'rare',crop:{x:50,y:50,z:1}},log:[],q:''};
const $=s=>document.querySelector(s);
const ch=id=>C.find(c=>c.id===id)||C[0];
const fmt=n=>Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(Number(n||0));
const num=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0});
const score=c=>Number(c.p||0)+Number(c.d||0)+Number(c.s||0);
const income=id=>state.cards.filter(c=>c.cid===id&&c.equipped).reduce((s,c)=>s+Number(c.passive||0),0);
function h(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(url,opt={}){let res=await fetch(url,{cache:'no-store',...opt}),data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data}
function cache(){try{if(user)localStorage['ctcg:'+user.id]=JSON.stringify(state)}catch(e){}}
function cropOf(c){let r=(c&&c.crop)||{};return{x:Number(r.x??50),y:Number(r.y??50),z:Number(r.z??1)}}
function cropStyle(c){let r=cropOf(c);return`object-position:${r.x}% ${r.y}%;transform:scale(${r.z});transform-origin:${r.x}% ${r.y}%`}
function title(id){let m={cydney:'Kitchen Authority',sterling:'Scope Creep Prophet',ryan:'Belligerent Min-Maxer',gabi:'Sourdough Spirit',cooper:'Wrong Quest Champion',kenly:'Decisive Comment',ashley:'Softball Cannon'};return ch(id).name+', '+m[id]}
function total(){return C.reduce((s,c)=>s+Number(state.tokens[c.id]||0)*Number(state.prices[c.id]||0),Number(state.cash||0))}
function previewCard(){let d=state.draft,cid=d.cid||'cydney';return{id:'preview',cid,title:d.title||title(cid),tag:d.tag||'Battle',rar:d.prev||'rare',p:'??',d:'??',s:'??',passive:'?',effect:'Server rolls final stats when minted.',img,crop:cropOf(d)}}
function cardHtml(c,big=false){let cc=ch(c.cid),rr=R[c.rar]||R.rare,imgTag=c.img?`<img src="${h(c.img)}" style="${cropStyle(c)}">`:`<div class="ph"><b>${cc.in}</b></div>`;return`<article class="card ${big?'bigcard':''}" style="--a:${cc.a};--r:${rr[2]}"><div class="art">${imgTag}</div><div class="line"></div><div class="ctop"><strong>${h((c.title||'Untitled').slice(0,big?34:20))}</strong><span class="badge">${rr[0]}</span></div>${c.equipped?'<span class="eq">Equipped</span>':''}<div class="stats"><div><small>POW</small><b>${c.p}</b></div><div><small>DEF</small><b>${c.d}</b></div><div><small>SPD</small><b>${c.s}</b></div></div><p class="fx">${h(c.effect||E[c.cid]||'Effect')}</p><div class="cbot"><span>+${c.passive}/min</span>${c.id==='preview'?'':`<button data-eq="${c.id}">${c.equipped?'Unequip':'Equip'}</button>`}</div></article>`}
function shell(content){return`<header class="top"><button class="brand" data-page="collection">Commune TCG<small>${h(user?.displayName||'')} Vault</small></button><nav class="tabs">${['collection','mint','battle','market','tokens'].map(p=>`<button class="${state.page===p?'on':''}" data-page="${p}">${p==='mint'?'Mint Card':p[0].toUpperCase()+p.slice(1)}</button>`).join('')}</nav><button class="btn" id="sync">Sync</button><button class="btn" id="logout">Switch Vault</button></header><div class="layout"><aside><div class="rank">${h(user?.displayName||'Vault')} Vault<small>Session active</small></div>${C.map(c=>`<button class="charbtn ${state.sel===c.id?'on':''}" data-char="${c.id}"><span class="av" style="--a:${c.a}">${c.in}</span>${c.name}</button>`).join('')}</aside><main class="content">${content}</main></div>`}
function strip(){let items=C.map(c=>`<div class="tok"><span class="coin" style="--a:${c.a}">${c.in}</span><span>${c.name}</span><b>${fmt(state.tokens[c.id])}</b><small>+${income(c.id)}/m</small></div>`).join('');return`<div class="strip"><div class="ticker"><div class="tickerGroup">${items}</div><div class="tickerGroup" aria-hidden="true">${items}</div></div></div>`}
function collection(){let q=(state.q||'').toLowerCase();return shell(strip()+`<div class="head"><div><h1>Card Collection</h1><p>${state.cards.length} Cards Collected · $${num(total())} Vault Value</p></div><div class="row"><button class="gold" data-page="mint">Mint Card</button></div></div><div class="sections">${C.map(c=>section(c,q)).join('')}</div>`)}
function section(c,q){let cards=state.cards.filter(x=>x.cid===c.id&&(!q||(String(x.title)+String(x.tag)+String(x.effect)+c.name).toLowerCase().includes(q))),best=cards.slice().sort((a,b)=>score(b)-score(a))[0],eq=cards.filter(x=>x.equipped);return`<section class="section"><div class="sectiontop"><div class="title"><div class="big" style="--a:${c.a}">${c.in}</div><div><h2>${c.name}</h2><p>${cards.length} Cards · +${income(c.id)}/min Passive</p></div></div><div class="slots"><div class="strong">Strongest Card<b>${best?'POW '+best.p:'None'}</b></div>${[0,1,2].map(i=>eq[i]?`<div class="slot">${eq[i].img?`<img src="${h(eq[i].img)}">`:ch(eq[i].cid).in}</div>`:'<div class="empty">+</div>').join('')}</div></div>${['legendary','rare','uncommon','common'].map(r=>grp(r,cards.filter(x=>x.rar===r),c)).join('')}</section>`}
function grp(r,cards,c){return`<div class="rgrp" style="--r:${R[r][2]}"><div class="rlabel">${R[r][0].toUpperCase()}</div><div class="grid">${cards.length?cards.map(x=>cardHtml(x)).join(''):`<div class="emptymsg">No ${R[r][0]} ${c.name} Cards Yet</div>`}</div></div>`}
function mint(){let d=state.draft,cc=ch(d.cid||'cydney'),cr=cropOf(d);return shell(`<div class="mint"><section class="stack"><div class="head"><div><h1>Forge New Identity</h1><p>Server rolls the final card when you mint.</p></div></div><div class="panel"><div class="label">Upload Artwork</div><label class="upload">${img?`<img src="${img}" style="${cropStyle({crop:cr})}">`:'<div><div style="font-size:2rem">☁</div><b>Click to upload art</b><br><small>PNG, JPG, or WEBP</small></div>'}<input id="up" type="file" accept="image/png,image/jpeg,image/webp"></label>${img?`<div class="cropGrid"><label>Horizontal<input id="cx" type="range" min="0" max="100" value="${cr.x}"></label><label>Vertical<input id="cy" type="range" min="0" max="100" value="${cr.y}"></label><label>Zoom<input id="cz" type="range" min="100" max="220" value="${Math.round(cr.z*100)}"></label><button class="btn" id="resetCrop" type="button">Reset</button></div>`:''}</div><div class="panel"><div class="label">Select Character</div><div class="tiles">${C.map(c=>`<button class="tile ${d.cid===c.id?'on':''}" data-draft="${c.id}" style="--a:${c.a}"><i>${c.in}</i><b>${c.name}</b></button>`).join('')}</div></div><div class="panel form"><label><span>Card Title</span><input id="ct" value="${h(d.title||'')}"></label><label><span>Flavor Tag</span><select id="tag">${tags.map(t=>`<option ${d.tag===t?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="row"><div class="cost"><span class="coin" style="--a:${cc.a}">${cc.in}</span><div><small>Mint Cost</small><strong>500 ${cc.name} Tokens</strong></div><div><small>Balance</small><strong>${fmt(state.tokens[cc.id])}</strong></div></div><button class="gold" id="mintBtn">Mint Card</button></div></section><aside class="preview"><div class="label">Preview</div>${cardHtml(previewCard(),true)}</aside></div>`)}
function battle(){return shell(`<div class="head"><div><h1>Battle Arena</h1><p>Fight random opponents. Rewards are paid by the server.</p></div><button class="gold" id="fight">Start Battle</button></div><div class="battle">${state.cards.length?state.cards.map(c=>cardHtml(c)).join(''):'<div class="box">Mint a card before battling.</div>'}</div><div class="log">${(state.log||[]).map(x=>`<div class="${x.win?'':'loss'}"><b>${x.win?'Victory':'Defeat'}</b><br>${h(x.txt)}</div>`).join('')||'<div>No battles yet.</div>'}</div>`)}
function market(){return shell(`<div class="head"><div><h1>Token Market</h1><p>Shared prices. Everyone sees the same market.</p></div><button class="btn">Cash: $${num(state.cash)}</button></div><div class="market">${C.map(c=>`<article class="box" style="--a:${c.a}"><div class="row"><span class="coin" style="--a:${c.a}">${c.in}</span><b>${c.name}</b></div><h3>$${Number(state.prices[c.id]||0).toFixed(2)}</h3><p>${fmt(state.tokens[c.id])} tokens</p><div class="row"><button class="btn" data-buy="${c.id}">Buy 10</button><button class="btn" data-sell="${c.id}">Sell 10</button></div></article>`).join('')}</div>`)}
function tokens(){return shell(`<div class="head"><div><h1>Token Vault</h1><p>Balances, passive income, and current market price.</p></div></div><div class="tokens">${C.map(c=>`<article class="box" style="--a:${c.a}"><div class="row"><div class="big" style="--a:${c.a}">${c.in}</div><div><h2>${c.name}</h2><p>${num(state.tokens[c.id])} Tokens</p><p>+${income(c.id)}/min · Market $${Number(state.prices[c.id]||0).toFixed(2)}</p></div></div></article>`).join('')}</div>`)}
function render(){if(!user)return renderLogin();$('#app').innerHTML=({collection,mint,battle,market,tokens}[state.page]||collection)();bind()}
function renderLogin(){let u=accounts.find(a=>a.id===selected)||accounts[0];if(!u){$('#app').innerHTML='<div class="auth"><div class="authCard"><h1>Choose Your Vault</h1><p>Loading accounts...</p><div class="err">'+h(authErr)+'</div></div></div>';return}selected=u.id;let setup=!u.pinSet;$('#app').innerHTML=`<div class="auth"><div class="authCard"><h1>Choose Your Vault</h1><p>Select your account. First entry creates a 4-digit Vault PIN.</p><div class="acctGrid">${accounts.map(a=>`<button class="acct ${a.id===u.id?'on':''}" data-acct="${a.id}" style="--a:${a.color}"><i>${a.initials}</i>${a.displayName}<br><small>${a.pinSet?'PIN SET':'SETUP'}</small></button>`).join('')}</div><form id="auth"><div class="label">${setup?'Set':'Enter'} 4-digit PIN for ${u.displayName}</div><div class="pin"><input id="pin" type="password" inputmode="numeric" maxlength="4" autocomplete="off" placeholder="••••">${setup?'<input id="pin2" type="password" inputmode="numeric" maxlength="4" autocomplete="off" placeholder="confirm">':''}<button class="gold" ${busy?'disabled':''}>${setup?'Create PIN':'Enter Vault'}</button></div><div class="err">${h(authErr)}</div></form></div></div>`;bindLogin()}
function bindLogin(){document.querySelectorAll('[data-acct]').forEach(b=>b.onclick=()=>{selected=b.dataset.acct;authErr='';renderLogin()});let f=$('#auth');if(f)f.onsubmit=e=>{e.preventDefault();submitAuth()}}
async function loadAccounts(){let d=await api('/api/auth/users');accounts=d.users||[];if(!selected&&accounts[0])selected=accounts[0].id}
async function submitAuth(){try{let u=accounts.find(a=>a.id===selected)||accounts[0],pin=$('#pin').value;if(!/^\d{4}$/.test(pin)){authErr='Use exactly 4 digits.';renderLogin();return}let body={userId:u.id,pin},url='/api/auth/login';if(!u.pinSet){let c=$('#pin2').value;if(c!==pin){authErr='PINs do not match.';renderLogin();return}body.confirm=c;url='/api/auth/setup-pin'}busy=true;renderLogin();let d=await api(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});user=d.user;busy=false;await loadState()}catch(e){busy=false;authErr=e.message;await loadAccounts().catch(()=>{});renderLogin()}}
async function loadAuth(){try{let r=await fetch('/api/auth/me',{cache:'no-store'}),d=await r.json().catch(()=>({}));if(r.ok&&d.user){user=d.user;await loadState();return}}catch(e){}try{await loadAccounts()}catch(e){authErr=e.message}render()}
async function logout(){try{await api('/api/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(state)})}catch(e){}try{await fetch('/api/auth/logout',{method:'POST'})}catch(e){}user=null;selected=null;await loadAccounts().catch(e=>authErr=e.message);render()}
async function loadState(){try{let d=await api('/api/state');user=d.user||user;state={...state,...d.state};cache();render()}catch(e){authErr=e.message;user=null;await loadAccounts().catch(()=>{});render()}}
function queueMeta(){clearTimeout(timer);timer=setTimeout(()=>api('/api/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(state)}).catch(console.warn),900)}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;queueMeta();render()});document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{state.sel=b.dataset.char;state.draft.cid=b.dataset.char;queueMeta();render()});let lo=$('#logout');if(lo)lo.onclick=logout;let sy=$('#sync');if(sy)sy.onclick=()=>loadState();document.querySelectorAll('[data-eq]').forEach(b=>b.onclick=async e=>{e.stopPropagation();let c=state.cards.find(x=>x.id===b.dataset.eq);try{await api(c&&c.equipped?'/api/cards/unequip':'/api/cards/equip',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:b.dataset.eq})});await loadState()}catch(err){alert(err.message)}});document.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>{let id=b.dataset.draft;state.draft.cid=id;state.draft.title=title(id);queueMeta();render()});let up=$('#up');if(up)up.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{img=r.result;state.draft.crop={x:50,y:50,z:1};render()};r.readAsDataURL(f)};let ct=$('#ct');if(ct)ct.oninput=()=>{state.draft.title=ct.value;queueMeta()};let tag=$('#tag');if(tag)tag.onchange=()=>{state.draft.tag=tag.value;queueMeta();render()};let cx=$('#cx'),cy=$('#cy'),cz=$('#cz'),rs=$('#resetCrop');if(cx)cx.oninput=()=>{state.draft.crop={...cropOf(state.draft),x:Number(cx.value)};render()};if(cy)cy.oninput=()=>{state.draft.crop={...cropOf(state.draft),y:Number(cy.value)};render()};if(cz)cz.oninput=()=>{state.draft.crop={...cropOf(state.draft),z:Number(cz.value)/100};render()};if(rs)rs.onclick=()=>{state.draft.crop={x:50,y:50,z:1};render()};let mb=$('#mintBtn');if(mb)mb.onclick=mintCard;let f=$('#fight');if(f)f.onclick=async()=>{try{await api('/api/battle/fight',{method:'POST'});await loadState()}catch(e){alert(e.message)}};document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=async()=>{try{await api('/api/market/buy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:b.dataset.buy,qty:10})});await loadState()}catch(e){alert(e.message)}});document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=async()=>{try{await api('/api/market/sell',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:b.dataset.sell,qty:10})});await loadState()}catch(e){alert(e.message)}})}
async function mintCard(){try{let d=state.draft,art=null,key=null;if(img){let up=await api('/api/upload',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dataUrl:img,cid:d.cid,id:crypto.randomUUID()})});art=up.url;key=up.key}await api('/api/cards/mint',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({cid:d.cid,title:d.title,tag:d.tag,img:art,imageKey:key,crop:cropOf(d)})});img=null;state.page='collection';state.sel=d.cid;await loadState()}catch(e){alert(e.message)}}
setInterval(()=>{if(user)loadState()},30000);
loadAuth();
