let cropTouchMoved=false;
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function applyDraftCropLive(){let cr=cropOf(state.draft);let style=`object-position:${cr.x}% ${cr.y}%;transform:scale(${cr.z});transform-origin:${cr.x}% ${cr.y}%`;document.querySelectorAll('.upload img,.bigcard .art img').forEach(im=>{im.style.objectPosition=`${cr.x}% ${cr.y}%`;im.style.transform=`scale(${cr.z})`;im.style.transformOrigin=`${cr.x}% ${cr.y}%`});let cx=document.getElementById('cx'),cy=document.getElementById('cy'),cz=document.getElementById('cz');if(cx)cx.value=Math.round(cr.x);if(cy)cy.value=Math.round(cr.y);if(cz)cz.value=Math.round(cr.z*100)}
function setDraftCrop(crop){state.draft.crop={x:clamp(crop.x,0,100),y:clamp(crop.y,0,100),z:clamp(crop.z,1,2.2)};applyDraftCropLive()}
function setupTouchCropper(){let box=document.querySelector('.upload');if(!box||!img||box.dataset.touchCropReady)return;box.dataset.touchCropReady='1';box.classList.add('cropTouch');let note=document.createElement('p');note.className='cropTouchNote';note.innerHTML='<b>Mobile crop:</b> drag to reposition, pinch to zoom, double tap to reset.';box.insertAdjacentElement('afterend',note);let pts=new Map(),base=cropOf(state.draft),startPoint=null,startMid=null,startDist=0,lastTap=0,downPoint=null;
function point(e){return{x:e.clientX,y:e.clientY}}
function updateBase(){base=cropOf(state.draft)}
box.addEventListener('click',e=>{if(cropTouchMoved){e.preventDefault();e.stopPropagation();cropTouchMoved=false}},true);
box.addEventListener('pointerdown',e=>{if(!img)return;let now=Date.now();if(now-lastTap<320){e.preventDefault();state.draft.crop={x:50,y:50,z:1};applyDraftCropLive();queueMeta();lastTap=0;return}lastTap=now;downPoint=point(e);pts.set(e.pointerId,downPoint);box.setPointerCapture?.(e.pointerId);updateBase();if(pts.size===1){startPoint=downPoint}else if(pts.size===2){let a=[...pts.values()];startMid=mid(a[0],a[1]);startDist=Math.max(1,dist(a[0],a[1]))}e.preventDefault()},{passive:false});
box.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId))return;let p=point(e),old=pts.get(e.pointerId);pts.set(e.pointerId,p);if(downPoint&&dist(downPoint,p)>4)cropTouchMoved=true;let rect=box.getBoundingClientRect();if(pts.size===1&&startPoint){let dx=p.x-startPoint.x,dy=p.y-startPoint.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z})}else if(pts.size>=2){let a=[...pts.values()],m=mid(a[0],a[1]),d=Math.max(1,dist(a[0],a[1])),dx=m.x-startMid.x,dy=m.y-startMid.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z*(d/startDist)})}e.preventDefault()},{passive:false});
function end(e){if(pts.has(e.pointerId))pts.delete(e.pointerId);updateBase();if(pts.size===1){startPoint=[...pts.values()][0]}else if(pts.size>=2){let a=[...pts.values()];startMid=mid(a[0],a[1]);startDist=Math.max(1,dist(a[0],a[1]))}queueMeta()}
box.addEventListener('pointerup',end);box.addEventListener('pointercancel',end);box.addEventListener('lostpointercapture',end)}
const originalBind=bind;bind=function(){originalBind();setupTouchCropper()};
