let cropTouchMoved=false;
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function applyDraftCropLive(){let cr=cropOf(state.draft);document.querySelectorAll('.upload img,.bigcard .art img').forEach(im=>{im.style.objectPosition=`${cr.x}% ${cr.y}%`;im.style.transform=`scale(${cr.z})`;im.style.transformOrigin=`${cr.x}% ${cr.y}%`});let cx=document.getElementById('cx'),cy=document.getElementById('cy'),cz=document.getElementById('cz');if(cx)cx.value=Math.round(cr.x);if(cy)cy.value=Math.round(cr.y);if(cz)cz.value=Math.round(cr.z*100)}
function setDraftCrop(crop){state.draft.crop={x:clamp(crop.x,0,100),y:clamp(crop.y,0,100),z:clamp(crop.z,1,3.2)};applyDraftCropLive()}
async function resizeImageFile(file){return new Promise((resolve,reject)=>{let reader=new FileReader();reader.onerror=()=>reject(new Error('Could not read image'));reader.onload=()=>{let source=reader.result,im=new Image();im.onerror=()=>reject(new Error('Could not load image'));im.onload=()=>{let max=900,w=im.naturalWidth,h=im.naturalHeight,scale=Math.min(1,max/Math.max(w,h));let cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale));let canvas=document.createElement('canvas');canvas.width=cw;canvas.height=ch;let ctx=canvas.getContext('2d');ctx.fillStyle='#101326';ctx.fillRect(0,0,cw,ch);ctx.drawImage(im,0,0,cw,ch);resolve(canvas.toDataURL('image/jpeg',0.82))};im.src=source};reader.readAsDataURL(file)})}
function replaceImagePicker(){let up=document.getElementById('up');if(!up||up.dataset.resizeReady)return;up.dataset.resizeReady='1';up.onchange=async e=>{let file=e.target.files&&e.target.files[0];if(!file)return;try{img=await resizeImageFile(file);state.draft.crop={x:50,y:50,z:1};render()}catch(err){alert(err.message||'Image failed')}}}
function setupTouchCropper(){replaceImagePicker();let box=document.querySelector('.upload');if(!box||!img||box.dataset.touchCropReady)return;box.dataset.touchCropReady='1';box.classList.add('cropTouch');let grid=document.querySelector('.cropGrid');if(grid)grid.style.display='none';let input=box.querySelector('input');let note=document.createElement('p');note.className='cropTouchNote';note.innerHTML='<b>Crop:</b> drag with one finger, pinch with two fingers, double tap to reset. <button class="btn miniChange" type="button">Change Image</button>';box.insertAdjacentElement('afterend',note);let change=note.querySelector('button');if(change&&input)change.onclick=()=>input.click();let base=cropOf(state.draft),startPoint=null,startMid=null,startDist=1,lastTap=0,points=new Map(),gestureBase=null;
function pointFromTouch(t){return{x:t.clientX,y:t.clientY}}
function pointFromPointer(e){return{x:e.clientX,y:e.clientY}}
function beginFromTouches(touches){base=cropOf(state.draft);if(touches.length===1){startPoint=pointFromTouch(touches[0])}else if(touches.length>=2){let a=pointFromTouch(touches[0]),b=pointFromTouch(touches[1]);startMid=mid(a,b);startDist=Math.max(1,dist(a,b))}}
function beginFromPointers(){base=cropOf(state.draft);let arr=[...points.values()];if(arr.length===1){startPoint=arr[0]}else if(arr.length>=2){startMid=mid(arr[0],arr[1]);startDist=Math.max(1,dist(arr[0],arr[1]))}}
box.addEventListener('click',e=>{if(img&&e.target!==input){e.preventDefault();e.stopPropagation()}},true);
box.addEventListener('gesturestart',e=>{gestureBase=cropOf(state.draft);e.preventDefault()},{passive:false});
box.addEventListener('gesturechange',e=>{if(!gestureBase)return;setDraftCrop({...gestureBase,z:gestureBase.z*e.scale});e.preventDefault()},{passive:false});
box.addEventListener('gestureend',e=>{gestureBase=null;queueMeta();e.preventDefault()},{passive:false});
box.addEventListener('touchstart',e=>{if(!img)return;let now=Date.now();if(e.touches.length===1&&now-lastTap<300){state.draft.crop={x:50,y:50,z:1};applyDraftCropLive();queueMeta();lastTap=0;e.preventDefault();return}lastTap=now;beginFromTouches(e.touches);e.preventDefault()},{passive:false});
box.addEventListener('touchmove',e=>{if(!img)return;let rect=box.getBoundingClientRect();if(e.touches.length===1&&startPoint){let p=pointFromTouch(e.touches[0]),dx=p.x-startPoint.x,dy=p.y-startPoint.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z})}else if(e.touches.length>=2&&startMid){let a=pointFromTouch(e.touches[0]),b=pointFromTouch(e.touches[1]),m=mid(a,b),d=Math.max(1,dist(a,b)),dx=m.x-startMid.x,dy=m.y-startMid.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z*(d/startDist)})}e.preventDefault()},{passive:false});
box.addEventListener('touchend',e=>{beginFromTouches(e.touches);queueMeta()},{passive:false});
box.addEventListener('pointerdown',e=>{if(!img)return;points.set(e.pointerId,pointFromPointer(e));box.setPointerCapture?.(e.pointerId);beginFromPointers();e.preventDefault()},{passive:false});
box.addEventListener('pointermove',e=>{if(!img||!points.has(e.pointerId))return;points.set(e.pointerId,pointFromPointer(e));let rect=box.getBoundingClientRect(),arr=[...points.values()];if(arr.length===1&&startPoint){let p=arr[0],dx=p.x-startPoint.x,dy=p.y-startPoint.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z})}else if(arr.length>=2&&startMid){let m=mid(arr[0],arr[1]),d=Math.max(1,dist(arr[0],arr[1])),dx=m.x-startMid.x,dy=m.y-startMid.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z*(d/startDist)})}e.preventDefault()},{passive:false});
function pointerEnd(e){if(points.has(e.pointerId))points.delete(e.pointerId);beginFromPointers();queueMeta()}
box.addEventListener('pointerup',pointerEnd);box.addEventListener('pointercancel',pointerEnd)}
const originalBind=bind;bind=function(){originalBind();setupTouchCropper()};
