let cropTouchMoved=false;
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function applyDraftCropLive(){let cr=cropOf(state.draft);document.querySelectorAll('.upload img,.bigcard .art img').forEach(im=>{im.style.objectPosition=`${cr.x}% ${cr.y}%`;im.style.transform=`scale(${cr.z})`;im.style.transformOrigin=`${cr.x}% ${cr.y}%`});let cx=document.getElementById('cx'),cy=document.getElementById('cy'),cz=document.getElementById('cz');if(cx)cx.value=Math.round(cr.x);if(cy)cy.value=Math.round(cr.y);if(cz)cz.value=Math.round(cr.z*100)}
function setDraftCrop(crop){state.draft.crop={x:clamp(crop.x,0,100),y:clamp(crop.y,0,100),z:clamp(crop.z,1,3.2)};applyDraftCropLive()}
async function resizeImageFile(file){return new Promise((resolve,reject)=>{let reader=new FileReader();reader.onerror=()=>reject(new Error('Could not read image'));reader.onload=()=>{let source=reader.result,im=new Image();im.onerror=()=>reject(new Error('Could not load image'));im.onload=()=>{let max=900,w=im.naturalWidth,h=im.naturalHeight,scale=Math.min(1,max/Math.max(w,h));let cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale));let canvas=document.createElement('canvas');canvas.width=cw;canvas.height=ch;let ctx=canvas.getContext('2d');ctx.fillStyle='#101326';ctx.fillRect(0,0,cw,ch);ctx.drawImage(im,0,0,cw,ch);resolve(canvas.toDataURL('image/jpeg',0.82))};im.src=source};reader.readAsDataURL(file)})}
function replaceImagePicker(){let up=document.getElementById('up');if(!up||up.dataset.resizeReady)return;up.dataset.resizeReady='1';up.onchange=async e=>{let file=e.target.files&&e.target.files[0];if(!file)return;try{img=await resizeImageFile(file);state.draft.crop={x:50,y:50,z:1};render()}catch(err){alert(err.message||'Image failed')}}}
function setupTouchCropper(){replaceImagePicker();let box=document.querySelector('.upload');if(!box||!img||box.dataset.touchCropReady)return;box.dataset.touchCropReady='1';box.classList.add('cropTouch');let grid=document.querySelector('.cropGrid');if(grid)grid.style.display='none';let input=box.querySelector('input');let note=document.createElement('p');note.className='cropTouchNote';note.innerHTML='<b>Crop:</b> drag with one finger, pinch with two fingers, double tap to reset. <button class="btn miniChange" type="button">Change Image</button>';box.insertAdjacentElement('afterend',note);let change=note.querySelector('button');if(change&&input)change.onclick=()=>input.click();let base=cropOf(state.draft),startPoint=null,startMid=null,startDist=1,lastTap=0,points=new Map(),gestureBase=null;
function pointFromTouch(t){return{x:t.clientX,y:t.clientY}}
function pointFromPointer(e){return{x:e.clientX,y:e.clientY}}
function beginFromTouches(touches){base=cropOf(state.draft);if(touches.length===1){startPoint=pointFromTouch(touches[0])}else if(touches.length>=2){let a=pointFromTouch(touches[0]),b=pointFromTouch(touches[1]);startMid=mid(a,b);startDist=Math.max(1,dist(a,b))}}
function beginFromPointers(){base=cropOf(state.draft);let arr=[...points.values()];if(arr.length===1){startPoint=arr[0]}else if(arr.length>=2){startMid=mid(arr[0],arr[1]);startDist=Math.max(1,dist(arr[0],arr[1]))}}
box.addEventListener('click',e=>{if(img&&e.target!==input){e.preventDefault();e.stopPropagation()}},true);
box.addEventListener('gesturestart',e=>{gestureBase=cropOf(state.draft);e.preventDefault()},{passive:false});
box.addEventListener('gesturechange',e=>{if(!gestureBase)return;setDraftCrop({...gestureBase,z:gestureBase.z*e.scale});e.preventDefault()},{passive:false});
box.addEventListener('gestureend',e=>{gestureBase=null;queueMeta();e.preventDefault()},{passive:false});
box.addEventListener('touchstart',e=>{if(!img)return;let now=Date.now();if(e.touches.length===1&&now-lastTap<300){state.draft.crop={x:50,y:50,z:1};applyDraftCropLive();queueMeta();lastTap=0;e.preventDefault();return}lastTap=now;beginFromTouches(e.touches);e.preventDefault()},{passive:false});
box.addEventListener('touchmove',e=>{if(!img)return;let rect=box.getBoundingClientRect();if(e.touches.length===1&&startPoint){let p=pointFromTouch(e.touches[0]),dx=p.x-startPoint.x,dy=p.y-startPoint.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z})}else if(e.touches.length>=2&&startMid){let a=pointFromTouch(e.touches[0]),b=pointFromTouch(e.touches[1]),m=mid(a,b),d=Math.max(1,dist(a,b)),dx=m.x-startMid.x,dy=m.y-startMid.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z*(d/startDist)})}e.preventDefault()},{passive:false});
box.addEventListener('touchend',e=>{beginFromTouches(e.touches);queueMeta()},{passive:false});
box.addEventListener('pointerdown',e=>{if(!img)return;points.set(e.pointerId,pointFromPointer(e));box.setPointerCapture?.(e.pointerId);beginFromPointers();e.preventDefault()},{passive:false});
box.addEventListener('pointermove',e=>{if(!img||!points.has(e.pointerId))return;points.set(e.pointerId,pointFromPointer(e));let rect=box.getBoundingClientRect(),arr=[...points.values()];if(arr.length===1&&startPoint){let p=arr[0],dx=p.x-startPoint.x,dy=p.y-startPoint.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z})}else if(arr.length>=2&&startMid){let m=mid(arr[0],arr[1]),d=Math.max(1,dist(arr[0],arr[1])),dx=m.x-startMid.x,dy=m.y-startMid.y;setDraftCrop({x:base.x-dx/rect.width*100,y:base.y-dy/rect.height*100,z:base.z*(d/startDist)})}e.preventDefault()},{passive:false});
function pointerEnd(e){if(points.has(e.pointerId))points.delete(e.pointerId);beginFromPointers();queueMeta()}
box.addEventListener('pointerup',pointerEnd);box.addEventListener('pointercancel',pointerEnd)}
const originalBind=bind;bind=function(){originalBind();setupTouchCropper()};
const originalCardHtml=cardHtml;
cardHtml=function(c,big=false){let html=originalCardHtml(c,big);if(c&&c.id&&c.id!=='preview')html=html.replace('<article class="card ',`<article tabindex="0" role="button" data-card-id="${h(c.id)}" class="card `);return html};
function rarityName(r){return (R[r]&&R[r][0])||r||'Unknown'}
function showCardDetail(id){let c=state.cards.find(x=>x.id===id);if(!c)return;let cc=ch(c.cid),rar=rarityName(c.rar),grade=Number(c.grade||score(c));let modal=document.createElement('div');modal.className='cardDetailBackdrop';modal.innerHTML=`<div class="cardDetailModal"><div class="cardDetailPreview">${cardHtml(c,true)}</div><aside class="cardDetailPanel"><div class="cardDetailTop"><div><span class="detailPill">${h(rar)} · ${h(cc.name)}</span><h2>${h(c.title||'Untitled')}</h2><p>${h(c.tag||'Battle')} · Owned by ${h(user?.displayName||'Current Vault')}</p></div><button class="cardDetailClose" type="button" data-detail-close>Close</button></div><div class="detailGrid"><div class="detailStat"><small>POW</small><b>${h(c.p)}</b></div><div class="detailStat"><small>DEF</small><b>${h(c.d)}</b></div><div class="detailStat"><small>SPD</small><b>${h(c.s)}</b></div></div><div class="detailGrid"><div class="detailBox"><small>Passive</small><b>+${h(c.passive)}/min</b></div><div class="detailBox"><small>Grade</small><b>${h(grade)}</b></div><div class="detailBox"><small>Status</small><b>${c.equipped?'Equipped':'Unequipped'}</b></div></div><div class="detailBox detailEffect"><small>Effect / Flavor</small><p>${h(c.effect||E[c.cid]||'No effect text.')}</p></div><div class="detailBox"><small>Card ID</small><p>${h(c.id)}</p></div><div class="detailActions"><button class="gold" type="button" data-detail-eq="${h(c.id)}">${c.equipped?'Unequip':'Equip'}</button><button class="btn" type="button" data-detail-close>Back to Collection</button></div></aside></div>`;document.body.appendChild(modal);modal.querySelectorAll('[data-detail-close]').forEach(b=>b.onclick=()=>modal.remove());modal.onclick=e=>{if(e.target===modal)modal.remove()};let eq=modal.querySelector('[data-detail-eq]');if(eq)eq.onclick=async()=>{try{await api(c.equipped?'/api/cards/unequip':'/api/cards/equip',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:c.id})});modal.remove();await loadState()}catch(err){alert(err.message)}}}
function setupCardDetails(){document.querySelectorAll('.grid .card[data-card-id],.battle .card[data-card-id]').forEach(card=>{if(card.dataset.detailReady)return;card.dataset.detailReady='1';card.addEventListener('click',e=>{if(e.target.closest('button'))return;showCardDetail(card.dataset.cardId)});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showCardDetail(card.dataset.cardId)}})})}
const detailBind=bind;bind=function(){detailBind();setupCardDetails()};
function orderedCharactersForSidebar(){let owner=user&&user.id,primary=C.find(c=>c.id===owner),rest=C.filter(c=>c.id!==owner).slice().sort((a,b)=>a.name.localeCompare(b.name));return primary?[primary,...rest]:rest}
shell=function(content){let allOn=state.sel==='all',ordered=orderedCharactersForSidebar();return`<header class="top"><button class="brand" data-page="collection">Commune TCG<small>${h(user?.displayName||'')} Vault</small></button><nav class="tabs">${['collection','mint','battle','market','tokens'].map(p=>`<button class="${state.page===p?'on':''}" data-page="${p}">${p==='mint'?'Mint Card':p[0].toUpperCase()+p.slice(1)}</button>`).join('')}</nav><button class="btn" id="sync">Sync</button><button class="btn" id="logout">Switch Vault</button></header><div class="layout"><aside><div class="rank">Characters<small>Filtering ${h(user?.displayName||'Vault')} Vault</small></div><button class="charbtn ${allOn?'on':''}" data-char="all"><span class="av" style="--a:#e9c349">ALL</span>All Characters</button>${ordered.map(c=>`<button class="charbtn ${state.sel===c.id?'on':''}" data-char="${c.id}"><span class="av" style="--a:${c.a}">${c.in}</span>${c.name}</button>`).join('')}</aside><main class="content">${content}</main></div>`};
