const MINT_FLAVOR_LIMIT=120;
function defaultFlavorForCharacter(id){return E[id]||'Flavor text'}
function cleanFlavorText(value){return String(value||'').slice(0,MINT_FLAVOR_LIMIT)}
function draftFlavor(){let d=state.draft||{};return cleanFlavorText(d.effect||d.flavorText||defaultFlavorForCharacter(d.cid||'cydney'))}
function ensureDraftFlavor(){state.draft=state.draft||{};if(!state.draft.effect&&!state.draft.flavorText)state.draft.effect=defaultFlavorForCharacter(state.draft.cid||'cydney')}
const mintFlavorOldPreviewCard=previewCard;
previewCard=function(){ensureDraftFlavor();let c=mintFlavorOldPreviewCard();c.effect=draftFlavor();return c}
const mintFlavorOldMint=mint;
mint=function(){ensureDraftFlavor();let d=state.draft,cc=ch(d.cid||'cydney'),cr=cropOf(d);return shell(`<div class="mint"><section class="stack"><div class="head"><div><h1>Forge New Identity</h1><p>Server rolls the final card when you mint.</p></div></div><div class="panel"><div class="label">Upload Artwork</div><label class="upload">${img?`<img src="${img}" style="${cropStyle({crop:cr})}">`:'<div><div style="font-size:2rem">☁</div><b>Click to upload art</b><br><small>PNG, JPG, or WEBP</small></div>'}<input id="up" type="file" accept="image/png,image/jpeg,image/webp"></label>${img?`<div class="cropGrid"><label>Horizontal<input id="cx" type="range" min="0" max="100" value="${cr.x}"></label><label>Vertical<input id="cy" type="range" min="0" max="100" value="${cr.y}"></label><label>Zoom<input id="cz" type="range" min="100" max="220" value="${Math.round(cr.z*100)}"></label><button class="btn" id="resetCrop" type="button">Reset</button></div>`:''}</div><div class="panel"><div class="label">Select Character</div><div class="tiles">${C.map(c=>`<button class="tile ${d.cid===c.id?'on':''}" data-draft="${c.id}" style="--a:${c.a}"><i>${c.in}</i><b>${c.name}</b></button>`).join('')}</div></div><div class="panel form mintFlavorForm"><label class="titleField"><span>Card Title</span><input id="ct" value="${h(d.title||'')}" maxlength="25"></label><label class="tagField"><span>Flavor Tag</span><select id="tag">${tags.map(t=>`<option ${d.tag===t?'selected':''}>${t}</option>`).join('')}</select></label><label class="flavorField"><span>Flavor Text</span><textarea id="flavorText" maxlength="${MINT_FLAVOR_LIMIT}" rows="3">${h(draftFlavor())}</textarea><small><span id="flavorCount">${draftFlavor().length}</span>/${MINT_FLAVOR_LIMIT}</small></label></div><div class="row"><div class="cost"><span class="coin" style="--a:${cc.a}">${cc.in}</span><div><small>Mint Cost</small><strong>500 ${cc.name} Tokens</strong></div><div><small>Balance</small><strong>${fmt(state.tokens[cc.id])}</strong></div></div><button class="gold" id="mintBtn">Mint Card</button></div></section><aside class="preview"><div class="label">Preview</div>${cardHtml(previewCard(),true)}</aside></div>`)}
function setupMintFlavorControls(){if(state.page!=='mint')return;ensureDraftFlavor();let flavor=document.getElementById('flavorText');if(flavor&&!flavor.dataset.ready){flavor.dataset.ready='1';flavor.oninput=()=>{state.draft.effect=cleanFlavorText(flavor.value);state.draft.flavorText=state.draft.effect;let count=document.getElementById('flavorCount');if(count)count.textContent=String(state.draft.effect.length);queueMeta();let preview=document.querySelector('.preview');if(preview)preview.innerHTML='<div class="label">Preview</div>'+cardHtml(previewCard(),true);scheduleTitleFit?.(preview)}}}
}
function relabelFlavorDetails(root=document){root.querySelectorAll('.detailEffect small').forEach(s=>{if(/effect\s*\/\s*flavor/i.test(s.textContent)||/effect/i.test(s.textContent))s.textContent='Flavor'});root.querySelectorAll('.detailEffect p').forEach(p=>{if(p.textContent==='No effect text.')p.textContent='No flavor text.'})}
const mintFlavorOldBind=bind;
bind=function(){mintFlavorOldBind();setupMintFlavorControls();relabelFlavorDetails()}
const mintFlavorOldMintCard=mintCard;
mintCard=async function(){try{ensureDraftFlavor();let d=state.draft,art=null,key=null;if(img){let up=await api('/api/upload',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dataUrl:img,cid:d.cid,id:crypto.randomUUID()})});art=up.url;key=up.key}await api('/api/cards/mint',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({cid:d.cid,title:d.title,tag:d.tag,effect:cleanFlavorText(d.effect||d.flavorText),flavorText:cleanFlavorText(d.effect||d.flavorText),img:art,imageKey:key,crop:cropOf(d)})});img=null;state.page='collection';state.sel=d.cid;await loadState()}catch(e){alert(e.message)}}
function injectMintFlavorStyles(){if(document.getElementById('ctcgMintFlavorStyles'))return;let style=document.createElement('style');style.id='ctcgMintFlavorStyles';style.textContent=`
.mintFlavorForm textarea{width:100%;min-height:92px;border:1px solid var(--line);border-radius:7px;padding:11px 12px;color:var(--text);background:#101326;resize:vertical;font:inherit}.mintFlavorForm .flavorField{grid-column:1/-1}.mintFlavorForm .flavorField small{display:block;margin-top:6px;text-align:right;color:#aeb2cc;font:900 .64rem 'JetBrains Mono',monospace}.cardDetailPanel .detailEffect small{text-transform:uppercase}@media(max-width:1080px){.mintFlavorForm{display:grid!important;grid-template-columns:1fr!important}.mintFlavorForm .titleField,.mintFlavorForm .tagField,.mintFlavorForm .flavorField{grid-column:1/-1!important;width:100%!important}.mintFlavorForm input#ct{width:100%!important;min-width:0!important;font-size:1rem}.mintFlavorForm select#tag,.mintFlavorForm textarea#flavorText{width:100%!important;min-width:0!important}}
`;document.head.appendChild(style)}
injectMintFlavorStyles();
new MutationObserver(mutations=>{for(const m of mutations){for(const n of m.addedNodes||[]){if(n.nodeType===1)relabelFlavorDetails(n)}}}).observe(document.body,{childList:true,subtree:true});