/* ============================================================================
   Admin Submission Detail Route
   Phase 10F.4 responsibility: show submission review detail and server-owned
   review actions while keeping approval rarity/stats generated by the backend.
   ============================================================================ */

import { renderCardFrame } from '../components/CardFrame.js';
import { escapeHtml, titleCase } from '../components/format.js';
import { fetchJson, getApiRoutes } from '../services/apiClient.js';

function formatStatus(value) {
  return titleCase(String(value || 'pending_review').replaceAll('_', ' '));
}

function formatBytes(value) {
  const bytes = Number(value || 0);
  if (!Number.isFinite(bytes) || bytes <= 0) return 'Unknown';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

function formatRarityReview(value) {
  return String(value || 'random') === 'random' ? 'Random on approval' : titleCase(value);
}

function isReviewable(submission) {
  return ['pending_review', 'needs_changes'].includes(submission.moderationStatus);
}

function getPayloadError(payload, response) {
  const parts = [payload?.error, payload?.detail].filter(Boolean);
  return parts.join(': ') || `Review action failed with ${response.status}`;
}

function getCreatorDisplayName(submission) {
  return String(
    submission.creatorDisplayName
      || submission.creatorDisplayNameOverride
      || submission.submitterDisplayName
      || submission.creatorDisplayName
      || submission.submitterUserId
      || 'Unknown'
  ).trim();
}

function submissionToPreviewCard(submission) {
  return {
    id: submission.id,
    name: submission.cardName,
    cid: submission.characterId,
    character: submission.characterId,
    characterId: submission.characterId,
    type: submission.cardType,
    category: submission.cardType,
    rarity: submission.raritySuggestion === 'random' ? 'common' : submission.raritySuggestion,
    symbol: '◆',
    ability: submission.abilityText || '',
    abilityIcon: '✦',
    stats: { pow: '?', def: '?', spd: '?' },
    owned: false,
    level: 1,
    copies: 0,
    flavor: submission.flavorText,
    imageKey: submission.imageKey,
    imageUrl: submission.imageUrl,
    crop: submission.cropJson,
  };
}

function renderDetailRow(label, value) {
  return `<div class="detail-row"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value || 'Not set')}</strong></div>`;
}

function renderReviewControls(submission) {
  if (!isReviewable(submission)) {
    return `
      <section class="glass-panel admin-panel">
        <span class="section-kicker">Review Closed</span>
        <h2 class="section-title">${escapeHtml(formatStatus(submission.moderationStatus))}</h2>
        <p class="hero-copy">This submission is no longer in a reviewable state. Creator editing is pre-approval only for now.</p>
      </section>
    `;
  }

  const creatorDisplayName = getCreatorDisplayName(submission);

  return `
    <section class="glass-panel admin-panel admin-card-editor-form" data-submission-review-panel data-submission-id="${escapeHtml(submission.id)}">
      <span class="section-kicker">Review Actions</span>
      <h2 class="section-title">Server-owned review</h2>
      <p class="hero-copy">Approve creates an unowned Library card row. Rarity and POW/DEF/SPD are rolled by the server during approval.</p>
      <label class="review-notes-label">
        <span>Creator</span>
        <input data-review-creator maxlength="120" value="${escapeHtml(creatorDisplayName)}" placeholder="Visible creator name" />
      </label>
      <label class="review-notes-label">
        <span>Review Notes</span>
        <textarea data-review-notes maxlength="500" placeholder="Optional note for this review action."></textarea>
      </label>
      <div class="action-row">
        <button class="button button-primary" type="button" data-review-action="approve">Approve to Library</button>
        <button class="button button-secondary" type="button" data-review-action="needs_changes">Needs Changes</button>
        <button class="button button-secondary" type="button" data-review-action="reject">Reject</button>
      </div>
      <div class="empty-note" data-review-status>Ready for review action. Creator override will be saved with the action.</div>
    </section>
  `;
}

async function loadSubmission(submissionId) {
  const routes = getApiRoutes();
  const payload = await fetchJson(routes.adminSubmission + '?id=' + encodeURIComponent(submissionId));
  if (!payload?.ok || !payload.submission) throw new Error(payload?.error || 'Submission detail was not returned.');
  return payload.submission;
}

export async function renderAdminSubmissionDetail({ params }) {
  const submissionId = params.submissionId;

  try {
    const submission = await loadSubmission(submissionId);
    const previewCard = submissionToPreviewCard(submission);
    const creatorDisplayName = getCreatorDisplayName(submission);

    return `
      <section class="hero-panel">
        <span class="section-kicker">Admin Review</span>
        <h2 class="hero-title">Submission Detail</h2>
        <p class="hero-copy">Approved submissions become Library cards. Rarity and battle stats are assigned only when you approve.</p>
        <div class="action-row">
          <a class="button button-secondary" href="#/admin">Back to Admin</a>
          <a class="button button-secondary" href="${escapeHtml(submission.imageUrl)}" target="_blank" rel="noreferrer">Open Image</a>
        </div>
      </section>

      <section class="detail-layout">
        <div class="detail-card-stage">
          ${renderCardFrame(previewCard, { density: 'showcase', context: 'library', showOwnership: false, showStats: false })}
        </div>

        <article class="detail-panel">
          <span class="section-kicker">${escapeHtml(formatStatus(submission.moderationStatus))}</span>
          <h2 class="detail-title">${escapeHtml(submission.cardName)}</h2>
          <div class="detail-list">
            ${renderDetailRow('Status', formatStatus(submission.moderationStatus))}
            ${renderDetailRow('Approved Card ID', submission.approvedCardId || 'Not approved')}
            ${renderDetailRow('Submitter', submission.submitterDisplayName)}
            ${renderDetailRow('Creator', creatorDisplayName)}
            ${renderDetailRow('Character', titleCase(submission.characterId))}
            ${renderDetailRow('Type', titleCase(submission.cardType))}
            ${renderDetailRow('Approval Rarity', formatRarityReview(submission.raritySuggestion))}
            ${renderDetailRow('Approval Stats', 'Generated from approved rarity')}
            ${renderDetailRow('Flavor', submission.flavorText)}
            ${renderDetailRow('Ability', submission.abilityText || 'None')}
            ${renderDetailRow('Review Notes', submission.reviewNotes || 'None')}
            ${renderDetailRow('Image Key', submission.imageKey)}
            ${renderDetailRow('Original Filename', submission.imageOriginalName)}
            ${renderDetailRow('Image Type', submission.imageMimeType)}
            ${renderDetailRow('Image Size', formatBytes(submission.imageSizeBytes))}
            ${renderDetailRow('Created', submission.createdAt)}
            ${renderDetailRow('Updated', submission.updatedAt)}
          </div>
        </article>
      </section>

      ${renderReviewControls(submission)}
    `;
  } catch (error) {
    return `
      <section class="hero-panel">
        <span class="section-kicker">Admin Review</span>
        <h2 class="hero-title">Submission not found.</h2>
        <p class="hero-copy">${escapeHtml(error.message)}</p>
        <div class="action-row"><a class="button button-secondary" href="#/admin">Back to Admin</a></div>
      </section>
    `;
  }
}

export function initAdminSubmissionDetail(root) {
  const panel = root.querySelector('[data-submission-review-panel]');
  if (!panel) return;

  const status = panel.querySelector('[data-review-status]');
  const notes = panel.querySelector('[data-review-notes]');
  const creator = panel.querySelector('[data-review-creator]');

  panel.querySelectorAll('[data-review-action]').forEach((button) => {
    button.addEventListener('click', async () => {
      const action = button.getAttribute('data-review-action');
      const creatorDisplayName = creator?.value?.trim() || '';
      status.textContent = 'Applying review action and saving creator...';

      try {
        const routes = getApiRoutes();
        const response = await fetch(routes.adminSubmissionAction, {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            id: panel.getAttribute('data-submission-id'),
            action,
            reviewNotes: notes.value,
            creatorDisplayName,
          }),
        });
        const payload = await response.json().catch(() => null);
        if (!response.ok || !payload?.ok) throw new Error(getPayloadError(payload, response));

        const roll = payload.approvalProfile;
        const creatorMessage = payload.creatorDisplayName ? ` Creator saved as ${payload.creatorDisplayName}.` : ' Creator saved.';
        status.textContent = roll
          ? `Approved: ${titleCase(roll.rarity)} · POW ${roll.stats.pow} / DEF ${roll.stats.def} / SPD ${roll.stats.spd}.${creatorMessage}`
          : 'Review action applied: ' + action.replaceAll('_', ' ') + '.' + creatorMessage;
        window.setTimeout(() => window.location.reload(), 900);
      } catch (error) {
        status.textContent = error.message;
      }
    });
  });
}
