import{CHARACTER_IDS,defaultPlayerMeta,ensureGameSchema,getSessionUser,json}from'../_shared/game.js';

function validSel(sel,oldSel){return sel==='all'||CHARACTER_IDS.includes(sel)?sel:(oldSel||'all')}
function validAiBattleMode(mode,oldMode){return mode==='manual'||mode==='auto'?mode:(oldMode||'auto')}
function cleanBattleSquad(list,oldList){return Array.isArray(list)?list.map(x=>String(x||'')).filter(Boolean).slice(0,3):(Array.isArray(oldList)?oldList:[])}
async function readMeta(env,user){let row=await env.DB.prepare('SELECT value FROM player_meta WHERE user_id=?').bind(user.id).first();if(!row)return defaultPlayerMeta(user.id);try{return{...defaultPlayerMeta(user.id),...JSON.parse(row.value)}}catch{return defaultPlayerMeta(user.id)}}
async function writeMeta(env,user,state){let old=await readMeta(env,user),meta={...old,page:state.page||old.page,sel:validSel(state.sel,old.sel),draft:state.draft||old.draft,log:Array.isArray(state.log)?state.log.slice(0,40):old.log,q:typeof state.q==='string'?state.q.slice(0,100):old.q,aiBattleSquadMode:validAiBattleMode(state.aiBattleSquadMode,old.aiBattleSquadMode),aiBattleSquad:cleanBattleSquad(state.aiBattleSquad,old.aiBattleSquad)};await env.DB.prepare("INSERT INTO player_meta (user_id,value,updated_at) VALUES (?,?,datetime('now')) ON CONFLICT(user_id) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(user.id,JSON.stringify(meta)).run()}
async function driftMarket(env){let rows=await env.DB.prepare('SELECT token_type,price,updated_at FROM market_prices').all(),now=Date.now(),oldest=0;for(let r of rows.results||[]){let t=Date.parse((r.updated_at||'').replace(' ','T')+'Z')||0;if(!oldest||t<oldest)oldest=t}if(oldest&&now-oldest<30000)return;let jobs=[];for(let r of rows.results||[]){let v=r.token_type==='cooper'?.14:r.token_type==='ryan'?.11:r.token_type==='cydney'?.06:.08,price=Math.max(.5,Number((Number(r.price||1)*(1+(Math.random()-.46)*v)).toFixed(2)));jobs.push(env.DB.prepare("UPDATE market_prices SET price=?,updated_at=datetime('now') WHERE token_type=?").bind(price,r.token_type))}if(jobs.length)await env.DB.batch(jobs)}
async function accrue(env,user,meta){let now=Date.now(),last=Number(meta.lastCollectedAt||now),mins=Math.max(0,Math.min(24*60,(now-last)/60000));if(mins<.05){return meta}let rows=await env.DB.prepare('SELECT card_json FROM cards WHERE owner_user_id=?').bind(user.id).all(),income=Object.fromEntries(CHARACTER_IDS.map(id=>[id,0]));for(let r of rows.results||[]){try{let c=JSON.parse(r.card_json);if(c.equipped)income[c.cid]=(income[c.cid]||0)+Number(c.passive||0)}catch{}}let jobs=[];for(let id of CHARACTER_IDS){let add=Number(((income[id]||0)*mins).toFixed(2));if(add>0)jobs.push(env.DB.prepare("UPDATE token_balances SET balance=balance+?,updated_at=datetime('now') WHERE user_id=? AND token_type=?").bind(add,user.id,id))}meta.lastCollectedAt=now;jobs.push(env.DB.prepare("INSERT INTO player_meta (user_id,value,updated_at) VALUES (?,?,datetime('now')) ON CONFLICT(user_id) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(user.id,JSON.stringify(meta)));await env.DB.batch(jobs);return meta}
async function readPlayerState(env,user){await driftMarket(env);let meta=await readMeta(env,user);meta.sel=validSel(meta.sel,'all');meta.aiBattleSquadMode=validAiBattleMode(meta.aiBattleSquadMode,'auto');meta.aiBattleSquad=cleanBattleSquad(meta.aiBattleSquad,[]);meta=await accrue(env,user,meta);let wallet=await env.DB.prepare('SELECT commune_cash FROM wallets WHERE user_id=?').bind(user.id).first(),br=await env.DB.prepare('SELECT token_type,balance FROM token_balances WHERE user_id=?').bind(user.id).all(),cr=await env.DB.prepare('SELECT card_json FROM cards WHERE owner_user_id=? ORDER BY created_at DESC').bind(user.id).all(),pr=await env.DB.prepare('SELECT token_type,price FROM market_prices').all(),tokens=Object.fromEntries(CHARACTER_IDS.map(id=>[id,0])),prices=Object.fromEntries(CHARACTER_IDS.map(id=>[id,1]));for(let r of br.results||[])tokens[r.token_type]=Number(r.balance||0);for(let r of pr.results||[])prices[r.token_type]=Number(r.price||1);let cards=(cr.results||[]).map(r=>{try{return JSON.parse(r.card_json)}catch{return null}}).filter(Boolean);return{...meta,cards,tokens,prices,cash:Number(wallet?.commune_cash??5000),user}}
export async function onRequestGet({request,env}){try{await ensureGameSchema(env);let user=await getSessionUser(request,env);if(!user)return json({error:'Not logged in'},401);return json({state:await readPlayerState(env,user),user})}catch(e){return json({error:e.message||'Failed to load state'},500)}}
export async function onRequestPost({request,env}){try{await ensureGameSchema(env);let user=await getSessionUser(request,env);if(!user)return json({error:'Not logged in'},401);let state=await request.json();await writeMeta(env,user,state);return json({ok:true})}catch(e){return json({error:e.message||'Failed to save state'},500)}}