const CHARS=['cydney','sterling','ryan','gabi','cooper','kenly','ashley'];
const N={cydney:'Cydney',sterling:'Sterling',ryan:'Ryan',gabi:'Gabi',cooper:'Cooper',kenly:'Kenly',ashley:'Ashley'};
const INIT={cydney:'CY',sterling:'ST',ryan:'RY',gabi:'GA',cooper:'CO',kenly:'KE',ashley:'AS'};
let state={tab:'overview',data:null,err:'',ok:'',query:'',modal:null};
const $=s=>document.querySelector(s),money=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(url,opt={}){let res=await fetch(url,{cache:'no-store',...opt}),data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data}
function post(url,body={}){return api(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})}
async function init(){try{await api('/api/admin/me');await load()}catch{renderLogin()}}
function renderLogin(){document.getElementById('adminApp').innerHTML=`<section class="login"><form class="loginCard" id="login"><h1>Commune TCG Admin</h1><p>Authorized game-master access only. Admin actions can permanently change player vaults.</p><input id="pw" type="password" placeholder="Admin password" autocomplete="current-password"><button class="btn primary" style="width:100%">Enter Admin Panel</button><div class="err">${esc(state.err)}</div></form></section>`;$('#login').onsubmit=async e=>{e.preventDefault();state.err='';try{await post('/api/admin/login',{password:$('#pw').value});await load()}catch(err){state.err=err.message;renderLogin()}}}
async function load(){state.data=await api('/api/admin/data');state.err='';render()}
function shell(content){let tabs=['overview','users','cards','market','tools','danger'];return`<div class="app"><aside class="side"><div class="logo">Commune TCG Admin<small>Game Master Control</small></div><nav class="nav">${tabs.map(t=>`<button class="${state.tab===t?'on':''}" data-tab="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</nav></aside><main class="main"><header class="top"><div><span class="badge">Production</span> <span class="pill">Admin Session</span></div><div class="tools"><button class="btn" id="refresh">Refresh</button><button class="btn ghost" id="logout">Logout</button></div></header><div class="content">${state.ok?`<div class="ok">${esc(state.ok)}</div>`:''}${state.err?`<div class="err">${esc(state.err)}</div>`:''}${content}</div></main></div>${state.modal?modalHtml():''}`}
function render(){let view={overview,users,cards,market,tools,danger}[state.tab]||overview;document.getElementById('adminApp').innerHTML=shell(view());bind()}
function overview(){let d=state.data,s=d.stats||{},recent=(d.cards||[]).slice(0,8);return`<div class="head"><h1>Command Center</h1><p>Global control surface for testing, balancing, fixing, and hard deletes.</p></div><div class="cards"><div class="stat"><span>Total Cards</span><b>${s.cards||0}</b></div><div class="stat"><span>Users</span><b>${s.users||0}</b></div><div class="stat"><span>Cash</span><b>$${money(s.totalCash)}</b></div><div class="stat"><span>Tokens</span><b>${money(s.totalTokens)}</b></div><div class="stat"><span>Top Market</span><b>${s.highestMarket?N[s.highestMarket.id]:'-'}</b></div></div><section class="panel"><div class="panelTop"><h2>Recently Minted</h2></div><div class="tableWrap"><table class="table"><thead><tr><th>Card</th><th>Owner</th><th>Type</th><th>Rarity</th><th>Stats</th><th>Passive</th></tr></thead><tbody>${recent.map(cardRowMini).join('')}</tbody></table></div></section>`}
function cardRowMini(c){return`<tr><td>${esc(c.title)}</td><td>${esc(N[c.owner]||c.owner)}</td><td>${esc(N[c.cid]||c.cid)}</td><td>${esc(c.rar)}</td><td>${c.p}/${c.d}/${c.s}</td><td>+${c.passive}/m</td></tr>`}
function users(){let d=state.data;return`<div class="head"><h1>Users</h1><p>Edit cash, token balances, and reset first-time PIN setup.</p></div><section class="panel"><div class="panelTop"><h2>Player Vaults</h2><button class="btn primary" id="saveUsers">Save All Edited Balances</button></div><div class="tableWrap"><table class="table"><thead><tr><th>User</th><th>Cash</th>${CHARS.map(c=>`<th>${INIT[c]}</th>`).join('')}<th>Cards</th><th>PIN</th><th>Actions</th></tr></thead><tbody>${d.users.map(u=>`<tr data-user="${u.id}"><td><b>${esc(u.displayName)}</b></td><td><input data-cash value="${u.cash}"></td>${CHARS.map(c=>`<td><input data-token="${c}" value="${u.tokens[c]||0}"></td>`).join('')}<td>${u.cardCount}</td><td>${u.pinSet?'Set':'Setup'}</td><td><button class="btn" data-reset-pin="${u.id}">Reset PIN</button></td></tr>`).join('')}</tbody></table></div></section>`}
function cards(){let q=state.query.toLowerCase(),items=(state.data.cards||[]).filter(c=>!q||String(c.title).toLowerCase().includes(q)||String(c.owner).includes(q)||String(c.cid).includes(q));return`<div class="head"><h1>Cards</h1><p>Edit card stats, ownership, rarity, passive rate, and hard delete bad cards.</p></div><section class="panel"><div class="panelTop"><h2>Card Registry</h2><div class="tools"><input class="search" id="search" placeholder="Search cards..." value="${esc(state.query)}"><button class="btn" id="clearSearch">Clear</button></div></div><div class="tableWrap"><table class="table"><thead><tr><th>Image</th><th>Title</th><th>Owner</th><th>Type</th><th>Rarity</th><th>POW</th><th>DEF</th><th>SPD</th><th>Passive</th><th>Eq</th><th>Actions</th></tr></thead><tbody>${items.map(c=>`<tr><td>${c.img?`<img class="thumb" src="${esc(c.img)}">`:'<div class="thumb"></div>'}</td><td><b>${esc(c.title)}</b></td><td>${esc(N[c.owner]||c.owner)}</td><td>${esc(N[c.cid]||c.cid)}</td><td>${esc(c.rar)}</td><td>${c.p}</td><td>${c.d}</td><td>${c.s}</td><td>${c.passive}</td><td>${c.equipped?'Yes':'No'}</td><td><button class="btn" data-edit-card="${c.id}">Edit</button> <button class="btn danger" data-del-card="${c.id}">Delete</button></td></tr>`).join('')}</tbody></table></div></section>`}
function market(){return`<div class="head"><h1>Market</h1><p>Edit global market prices used by everyone.</p></div><section class="panel"><div class="panelTop"><h2>Global Token Prices</h2><div class="tools"><button class="btn primary" id="saveMarket">Save All Prices</button><button class="btn" id="resetMarket">Reset Defaults</button></div></div><div class="tableWrap"><table class="table"><thead><tr><th>Token</th><th>Price</th><th>Updated</th></tr></thead><tbody>${state.data.market.map(m=>`<tr><td><b>${esc(N[m.id]||m.id)}</b></td><td><input data-market="${m.id}" value="${m.price}"></td><td>${esc(m.updatedAt||'')}</td></tr>`).join('')}</tbody></table></div></section>`}
function tools(){return`<div class="head"><h1>Tools</h1><p>Utility controls. More bulk actions can be added here as the game evolves.</p></div><section class="panel"><div class="panelTop"><h2>Available Now</h2></div><div style="padding:18px;display:grid;gap:12px"><p>Current admin powers: edit all cash/token balances, reset PINs, edit cards, hard delete cards, and edit/reset market prices.</p><p class="pill">Next likely additions: create test card, reset one user vault, delete all cards for one user.</p></div></section>`}
function danger(){return`<div class="head"><h1>Danger Zone</h1><p>Hard delete is enabled. Deleted cards are removed from D1 and their R2 image is deleted when possible.</p></div><section class="panel dangerZone"><div class="panelTop"><h2>Hard Delete Mode</h2></div><div style="padding:18px"><p>Use the Cards tab to permanently delete individual cards. Bulk destructive actions are intentionally not enabled yet.</p></div></section>`}
function modalHtml(){let m=state.modal;if(m.type==='delete')return`<div class="modalBackdrop"><div class="modal"><div class="modalHead"><h2>Permanently Delete Card?</h2><button class="btn" data-close>Close</button></div><div class="modalBody full"><p class="full">This cannot be undone. The card will be removed from the owner vault.</p><b class="full">${esc(m.card.title)}</b></div><div class="modalFoot"><button class="btn" data-close>Cancel</button><button class="btn danger" id="confirmDelete">Delete Permanently</button></div></div></div>`;let c=m.card;return`<div class="modalBackdrop"><div class="modal"><div class="modalHead"><h2>Edit Card</h2><button class="btn" data-close>Close</button></div><div class="modalBody"><div class="field full">${c.img?`<img src="${esc(c.img)}" style="max-height:220px;max-width:100%;object-fit:contain;border:1px solid var(--line);border-radius:8px">`:''}</div>${field('Title','title',c.title)}${selectField('Owner','owner',c.owner,CHARS)}${selectField('Character','cid',c.cid,CHARS)}${selectField('Rarity','rar',c.rar,['common','uncommon','rare','legendary'])}${field('POW','p',c.p,'number')}${field('DEF','d',c.d,'number')}${field('SPD','s',c.s,'number')}${field('Passive / min','passive',c.passive,'number')}${field('Tag','tag',c.tag)}<div class="field"><label>Equipped</label><select id="f-equipped"><option value="true" ${c.equipped?'selected':''}>Yes</option><option value="false" ${!c.equipped?'selected':''}>No</option></select></div><div class="field full"><label>Effect</label><textarea id="f-effect">${esc(c.effect||'')}</textarea></div></div><div class="modalFoot"><button class="btn" data-close>Cancel</button><button class="btn primary" id="saveCard">Save Changes</button></div></div></div>`}
function field(label,id,val,type='text'){return`<div class="field"><label>${label}</label><input id="f-${id}" type="${type}" value="${esc(val)}"></div>`}
function selectField(label,id,val,opts){return`<div class="field"><label>${label}</label><select id="f-${id}">${opts.map(o=>`<option value="${o}" ${o===val?'selected':''}>${N[o]||o}</option>`).join('')}</select></div>`}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.err='';state.ok='';render()});$('#refresh')?.addEventListener('click',load);$('#logout')?.addEventListener('click',async()=>{await fetch('/api/admin/logout',{method:'POST'});state.data=null;renderLogin()});$('#search')?.addEventListener('input',e=>{state.query=e.target.value;render()});$('#clearSearch')?.addEventListener('click',()=>{state.query='';render()});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{state.modal=null;render()});document.querySelectorAll('[data-edit-card]').forEach(b=>b.onclick=()=>{state.modal={type:'edit',card:state.data.cards.find(c=>c.id===b.dataset.editCard)};render()});document.querySelectorAll('[data-del-card]').forEach(b=>b.onclick=()=>{state.modal={type:'delete',card:state.data.cards.find(c=>c.id===b.dataset.delCard)};render()});$('#saveUsers')?.addEventListener('click',saveUsers);document.querySelectorAll('[data-reset-pin]').forEach(b=>b.onclick=()=>resetPin(b.dataset.resetPin));$('#saveMarket')?.addEventListener('click',saveMarket);$('#resetMarket')?.addEventListener('click',resetMarket);$('#saveCard')?.addEventListener('click',saveCard);$('#confirmDelete')?.addEventListener('click',deleteCard)}
async function saveUsers(){try{let rows=[...document.querySelectorAll('[data-user]')];for(let r of rows){let tokens={};r.querySelectorAll('[data-token]').forEach(i=>tokens[i.dataset.token]=Number(i.value));await post('/api/admin/user',{userId:r.dataset.user,cash:Number(r.querySelector('[data-cash]').value),tokens})}state.ok='User balances saved.';await load()}catch(e){state.err=e.message;render()}}
async function resetPin(id){if(!confirm(`Reset PIN for ${N[id]||id}?`))return;try{await post('/api/admin/user',{userId:id,resetPin:true});state.ok='PIN reset.';await load()}catch(e){state.err=e.message;render()}}
async function saveMarket(){try{let prices={};document.querySelectorAll('[data-market]').forEach(i=>prices[i.dataset.market]=Number(i.value));await post('/api/admin/market',{prices});state.ok='Market saved.';await load()}catch(e){state.err=e.message;render()}}
async function resetMarket(){if(!confirm('Reset all market prices to defaults?'))return;try{await post('/api/admin/market',{reset:true});state.ok='Market reset.';await load()}catch(e){state.err=e.message;render()}}
async function saveCard(){let c=state.modal.card;try{await post('/api/admin/card',{id:c.id,title:$('#f-title').value,owner:$('#f-owner').value,cid:$('#f-cid').value,rar:$('#f-rar').value,p:Number($('#f-p').value),d:Number($('#f-d').value),s:Number($('#f-s').value),passive:Number($('#f-passive').value),tag:$('#f-tag').value,equipped:$('#f-equipped').value==='true',effect:$('#f-effect').value});state.modal=null;state.ok='Card saved.';await load()}catch(e){state.err=e.message;render()}}
async function deleteCard(){let c=state.modal.card;try{await post('/api/admin/card-delete',{id:c.id});state.modal=null;state.ok='Card permanently deleted.';await load()}catch(e){state.err=e.message;render()}}
init();
