const CHARS=['cydney','sterling','ryan','gabi','cooper','kenly','ashley'];
const N={cydney:'Cydney',sterling:'Sterling',ryan:'Ryan',gabi:'Gabi',cooper:'Cooper',kenly:'Kenly',ashley:'Ashley'};
const INIT={cydney:'CY',sterling:'ST',ryan:'RY',gabi:'GA',cooper:'CO',kenly:'KE',ashley:'AS'};
const RAR=['common','uncommon','rare','legendary'];
const ENEMY_TYPES={random_encounter:'Random Encounter',household_chaos:'Household Chaos',yard_project:'Yard Project',rival_commune:'Rival Commune',boss_fight:'Boss Fight'};
const TAGS=['Champion','Guardian','Trickster','Wildcard','Support','Brawler','Oracle','Commander','Menace','Artisan','Mystic','Spicy'];
let state={tab:'overview',data:null,err:'',ok:'',query:'',enemyQuery:'',modal:null};
const $=s=>document.querySelector(s),money=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(url,opt={}){let res=await fetch(url,{cache:'no-store',...opt}),data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data}
function post(url,body={}){return api(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})}
async function init(){try{await api('/api/admin/me');await load()}catch{renderLogin()}}
function renderLogin(){document.getElementById('adminApp').innerHTML=`<section class="login"><form class="loginCard" id="login"><h1>Commune TCG Admin</h1><p>Authorized game-master access only. Admin actions can permanently change player vaults.</p><input id="pw" type="password" placeholder="Admin password" autocomplete="current-password"><button class="btn primary" style="width:100%">Enter Admin Panel</button><div class="err">${esc(state.err)}</div></form></section>`;$('#login').onsubmit=async e=>{e.preventDefault();state.err='';try{await post('/api/admin/login',{password:$('#pw').value});await load()}catch(err){state.err=err.message;renderLogin()}}}
async function load(){state.data=await api('/api/admin/data');state.err='';render()}
function shell(content){let tabs=['overview','users','cards','enemies','market','tools','danger'];return`<div class="app"><aside class="side"><div class="logo">Commune TCG Admin<small>Game Master Control</small></div><nav class="nav">${tabs.map(t=>`<button class="${state.tab===t?'on':''}" data-tab="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</nav></aside><main class="main"><header class="top"><div><span class="badge">Production</span> <span class="pill">Admin Session</span></div><div class="tools"><button class="btn" id="refresh">Refresh</button><button class="btn ghost" id="logout">Logout</button></div></header><div class="content">${state.ok?`<div class="ok">${esc(state.ok)}</div>`:''}${state.err?`<div class="err">${esc(state.err)}</div>`:''}${content}</div></main></div>${state.modal?modalHtml():''}`}
function render(){let view={overview,users,cards,enemies,market,tools,danger}[state.tab]||overview;document.getElementById('adminApp').innerHTML=shell(view());bind()}
function overview(){let d=state.data,s=d.stats||{},recent=(d.cards||[]).slice(0,8);return`<div class="head"><h1>Command Center</h1><p>Global control surface for testing, balancing, fixing, and hard deletes.</p></div><div class="cards"><div class="stat"><span>Total Cards</span><b>${s.cards||0}</b></div><div class="stat"><span>Enemy Templates</span><b>${s.enemyTemplates||0}</b></div><div class="stat"><span>Users</span><b>${s.users||0}</b></div><div class="stat"><span>Cash</span><b>$${money(s.totalCash)}</b></div><div class="stat"><span>Tokens</span><b>${money(s.totalTokens)}</b></div></div><section class="panel"><div class="panelTop"><h2>Recently Minted</h2></div><div class="tableWrap"><table class="table"><thead><tr><th>Card</th><th>Owner</th><th>Type</th><th>Rarity</th><th>Stats</th><th>Passive</th></tr></thead><tbody>${recent.map(cardRowMini).join('')}</tbody></table></div></section>`}
function cardRowMini(c){return`<tr><td>${esc(c.title)}</td><td>${esc(N[c.owner]||c.owner)}</td><td>${esc(N[c.cid]||c.cid)}</td><td>${esc(c.rar)}</td><td>${c.p}/${c.d}/${c.s}</td><td>+${c.passive}/m</td></tr>`}
function users(){let d=state.data;return`<div class="head"><h1>Users</h1><p>Edit cash, token balances, and reset first-time PIN setup.</p></div><section class="panel"><div class="panelTop"><h2>Player Vaults</h2><button class="btn primary" id="saveUsers">Save All Edited Balances</button></div><div class="tableWrap"><table class="table"><thead><tr><th>User</th><th>Cash</th>${CHARS.map(c=>`<th>${INIT[c]}</th>`).join('')}<th>Cards</th><th>PIN</th><th>Actions</th></tr></thead><tbody>${d.users.map(u=>`<tr data-user="${u.id}"><td><b>${esc(u.displayName)}</b></td><td><input data-cash value="${u.cash}"></td>${CHARS.map(c=>`<td><input data-token="${c}" value="${u.tokens[c]||0}"></td>`).join('')}<td>${u.cardCount}</td><td>${u.pinSet?'Set':'Setup'}</td><td><button class="btn" data-reset-pin="${u.id}">Reset PIN</button></td></tr>`).join('')}</tbody></table></div></section>`}
function cards(){let q=state.query.toLowerCase(),items=(state.data.cards||[]).filter(c=>!q||String(c.title).toLowerCase().includes(q)||String(c.owner).includes(q)||String(c.cid).includes(q));return`<div class="head"><h1>Cards</h1><p>Create cards for players, edit stats, ownership, images, rarity, passive rate, and hard delete bad cards.</p></div><section class="panel"><div class="panelTop"><h2>Card Registry</h2><div class="tools"><button class="btn primary" id="newCard">Create Card</button><input class="search" id="search" placeholder="Search cards..." value="${esc(state.query)}"><button class="btn" id="clearSearch">Clear</button></div></div><div class="tableWrap"><table class="table"><thead><tr><th>Image</th><th>Title</th><th>Owner</th><th>Type</th><th>Rarity</th><th>POW</th><th>DEF</th><th>SPD</th><th>Passive</th><th>Eq</th><th>Actions</th></tr></thead><tbody>${items.map(c=>`<tr><td>${c.img?`<img class="thumb" src="${esc(c.img)}">`:'<div class="thumb"></div>'}</td><td><b>${esc(c.title)}</b><br><small>${esc(c.tag||'')}</small></td><td>${esc(N[c.owner]||c.owner)}</td><td>${esc(N[c.cid]||c.cid)}</td><td>${esc(c.rar)}</td><td>${c.p}</td><td>${c.d}</td><td>${c.s}</td><td>${c.passive}</td><td>${c.equipped?'Yes':'No'}</td><td><button class="btn" data-edit-card="${c.id}">Edit</button> <button class="btn danger" data-del-card="${c.id}">Delete</button></td></tr>`).join('')}</tbody></table></div></section>`}
function enemies(){let q=state.enemyQuery.toLowerCase(),items=(state.data.enemyTemplates||[]).filter(t=>!q||String(t.title).toLowerCase().includes(q)||String(t.enemyType).includes(q)||String(t.cid).includes(q));return`<div class="head"><h1>Enemy Cards</h1><p>Curated bot enemy templates. Enabled templates are preferred in battles. Generated fallback still works when no template matches.</p></div><section class="panel"><div class="panelTop"><h2>Bot Enemy Templates</h2><div class="tools"><button class="btn primary" id="newEnemy">Create Enemy</button><input class="search" id="enemySearch" placeholder="Search enemies..." value="${esc(state.enemyQuery)}"><button class="btn" id="clearEnemySearch">Clear</button></div></div><div class="tableWrap"><table class="table"><thead><tr><th>Image</th><th>Title</th><th>Pool</th><th>Character</th><th>Rarity</th><th>Stats</th><th>Weight</th><th>Enabled</th><th>Actions</th></tr></thead><tbody>${items.map(t=>`<tr><td>${t.img?`<img class="thumb" src="${esc(t.img)}">`:'<div class="thumb"></div>'}</td><td><b>${esc(t.title)}</b><br><small>${esc(t.tag||'')}</small></td><td>${esc(ENEMY_TYPES[t.enemyType]||t.enemyType)}</td><td>${esc(N[t.cid]||t.cid)}</td><td>${esc(t.rar)}</td><td>${t.p}/${t.d}/${t.s}</td><td>${t.weight}</td><td>${t.enabled?'Yes':'No'}</td><td><button class="btn" data-edit-enemy="${t.id}">Edit</button> <button class="btn danger" data-del-enemy="${t.id}">Delete</button></td></tr>`).join('')}</tbody></table></div></section>`}
function market(){return`<div class="head"><h1>Market</h1><p>Edit global market prices used by everyone.</p></div><section class="panel"><div class="panelTop"><h2>Global Token Prices</h2><div class="tools"><button class="btn primary" id="saveMarket">Save All Prices</button><button class="btn" id="resetMarket">Reset Defaults</button></div></div><div class="tableWrap"><table class="table"><thead><tr><th>Token</th><th>Price</th><th>Updated</th></tr></thead><tbody>${state.data.market.map(m=>`<tr><td><b>${esc(N[m.id]||m.id)}</b></td><td><input data-market="${m.id}" value="${m.price}"></td><td>${esc(m.updatedAt||'')}</td></tr>`).join('')}</tbody></table></div></section>`}
function tools(){return`<div class="head"><h1>Tools</h1><p>Utility controls. More bulk actions can be added here as the game evolves.</p></div><section class="panel"><div class="panelTop"><h2>Available Now</h2></div><div style="padding:18px;display:grid;gap:12px"><p>Current admin powers: create/edit player cards, upload card images, edit bot enemy templates, edit cash/token balances, reset PINs, hard delete cards, and edit/reset market prices.</p><p class="pill">Next likely addition: full enemy image pool with reusable tagged assets.</p></div></section>`}
function danger(){return`<div class="head"><h1>Danger Zone</h1><p>Hard delete is enabled. Deleted cards are removed from D1 and their R2 image is deleted when possible.</p></div><section class="panel dangerZone"><div class="panelTop"><h2>Hard Delete Mode</h2></div><div style="padding:18px"><p>Use the Cards and Enemies tabs to permanently delete individual records. Bulk destructive actions are intentionally not enabled.</p></div></section>`}
function blankCard(){return{owner:'cydney',cid:'cydney',title:'Admin Card',tag:'Champion',rar:'rare',p:40,d:40,s:40,passive:0,equipped:false,effect:'',img:null,imageKey:null,crop:{x:50,y:50,z:1}}}
function blankEnemy(){return{enemyType:'random_encounter',cid:'cydney',title:'Enemy Template',tag:'AI Bot',rar:'common',p:30,d:30,s:30,passive:0,effect:'',img:null,imageKey:null,crop:{x:50,y:50,z:1},weight:1,enabled:true}}
function modalHtml(){let m=state.modal;if(m.type==='delete')return confirmModal('Permanently Delete Card?',`This cannot be undone. The card will be removed from the owner vault.<br><b>${esc(m.card.title)}</b>`,'confirmDelete','Delete Permanently');if(m.type==='enemyDelete')return confirmModal('Delete Enemy Template?',`This removes the bot template from future generation.<br><b>${esc(m.enemy.title)}</b>`,'confirmEnemyDelete','Delete Template');if(m.type==='enemyEdit'||m.type==='enemyNew')return enemyModal(m.enemy||blankEnemy(),m.type==='enemyNew');return cardModal(m.card||blankCard(),m.type==='cardNew')}
function confirmModal(title,body,id,button){return`<div class="modalBackdrop"><div class="modal"><div class="modalHead"><h2>${title}</h2><button class="btn" data-close>Close</button></div><div class="modalBody full"><p class="full">${body}</p></div><div class="modalFoot"><button class="btn" data-close>Cancel</button><button class="btn danger" id="${id}">${button}</button></div></div></div>`}
function cardModal(c,isNew){return`<div class="modalBackdrop"><div class="modal"><div class="modalHead"><h2>${isNew?'Create Player Card':'Edit Card'}</h2><button class="btn" data-close>Close</button></div><div class="modalBody">${imageField(c)}${field('Title','title',c.title)}${selectField('Owner','owner',c.owner,CHARS)}${selectField('Character','cid',c.cid,CHARS)}${selectField('Rarity','rar',c.rar,RAR)}${field('POW','p',c.p,'number')}${field('DEF','d',c.d,'number')}${field('SPD','s',c.s,'number')}${field('Passive / min','passive',c.passive,'number')}${selectField('Flavor Tag','tag',c.tag||'Champion',TAGS)}<div class="field"><label>Equipped</label><select id="f-equipped"><option value="true" ${c.equipped?'selected':''}>Yes</option><option value="false" ${!c.equipped?'selected':''}>No</option></select></div><div class="field full"><label>Flavor Text</label><textarea id="f-effect">${esc(c.effect||'')}</textarea></div></div><div class="modalFoot"><button class="btn" data-close>Cancel</button><button class="btn primary" id="${isNew?'createCard':'saveCard'}">${isNew?'Create Card':'Save Changes'}</button></div></div></div>`}
function enemyModal(e,isNew){return`<div class="modalBackdrop"><div class="modal"><div class="modalHead"><h2>${isNew?'Create Enemy Template':'Edit Enemy Template'}</h2><button class="btn" data-close>Close</button></div><div class="modalBody">${imageField(e)}${field('Title','title',e.title)}${selectField('Enemy Pool','enemyType',e.enemyType,Object.keys(ENEMY_TYPES),ENEMY_TYPES)}${selectField('Character','cid',e.cid,CHARS)}${selectField('Rarity','rar',e.rar,RAR)}${field('POW','p',e.p,'number')}${field('DEF','d',e.d,'number')}${field('SPD','s',e.s,'number')}${field('Passive visual','passive',e.passive||0,'number')}${field('Weight','weight',e.weight||1,'number')}<div class="field"><label>Enabled</label><select id="f-enabled"><option value="true" ${e.enabled?'selected':''}>Yes</option><option value="false" ${!e.enabled?'selected':''}>No</option></select></div>${field('Flavor Tag','tag',e.tag||'AI Bot')}<div class="field full"><label>Flavor Text</label><textarea id="f-effect">${esc(e.effect||'')}</textarea></div></div><div class="modalFoot"><button class="btn" data-close>Cancel</button><button class="btn primary" id="saveEnemy">Save Template</button></div></div></div>`}
function imageField(c){return`<div class="field full"><label>Image</label>${c.img?`<img src="${esc(c.img)}" style="max-height:220px;max-width:100%;object-fit:contain;border:1px solid var(--line);border-radius:8px">`:''}<input id="f-imgFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><small>Upload replaces the current image. Crop defaults to center.</small></div>`}
function field(label,id,val,type='text'){return`<div class="field"><label>${label}</label><input id="f-${id}" type="${type}" value="${esc(val)}"></div>`}
function selectField(label,id,val,opts,labels=N){return`<div class="field"><label>${label}</label><select id="f-${id}">${opts.map(o=>`<option value="${o}" ${o===val?'selected':''}>${esc(labels[o]||o)}</option>`).join('')}</select></div>`}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.err='';state.ok='';render()});$('#refresh')?.addEventListener('click',load);$('#logout')?.addEventListener('click',async()=>{await fetch('/api/admin/logout',{method:'POST'});state.data=null;renderLogin()});$('#search')?.addEventListener('input',e=>{state.query=e.target.value;render()});$('#clearSearch')?.addEventListener('click',()=>{state.query='';render()});$('#enemySearch')?.addEventListener('input',e=>{state.enemyQuery=e.target.value;render()});$('#clearEnemySearch')?.addEventListener('click',()=>{state.enemyQuery='';render()});$('#newCard')?.addEventListener('click',()=>{state.modal={type:'cardNew',card:blankCard()};render()});$('#newEnemy')?.addEventListener('click',()=>{state.modal={type:'enemyNew',enemy:blankEnemy()};render()});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{state.modal=null;render()});document.querySelectorAll('[data-edit-card]').forEach(b=>b.onclick=()=>{state.modal={type:'edit',card:state.data.cards.find(c=>c.id===b.dataset.editCard)};render()});document.querySelectorAll('[data-del-card]').forEach(b=>b.onclick=()=>{state.modal={type:'delete',card:state.data.cards.find(c=>c.id===b.dataset.delCard)};render()});document.querySelectorAll('[data-edit-enemy]').forEach(b=>b.onclick=()=>{state.modal={type:'enemyEdit',enemy:state.data.enemyTemplates.find(t=>t.id===b.dataset.editEnemy)};render()});document.querySelectorAll('[data-del-enemy]').forEach(b=>b.onclick=()=>{state.modal={type:'enemyDelete',enemy:state.data.enemyTemplates.find(t=>t.id===b.dataset.delEnemy)};render()});$('#saveUsers')?.addEventListener('click',saveUsers);document.querySelectorAll('[data-reset-pin]').forEach(b=>b.onclick=()=>resetPin(b.dataset.resetPin));$('#saveMarket')?.addEventListener('click',saveMarket);$('#resetMarket')?.addEventListener('click',resetMarket);$('#saveCard')?.addEventListener('click',saveCard);$('#createCard')?.addEventListener('click',createCard);$('#confirmDelete')?.addEventListener('click',deleteCard);$('#saveEnemy')?.addEventListener('click',saveEnemy);$('#confirmEnemyDelete')?.addEventListener('click',deleteEnemy)}
async function fileDataUrl(file){return new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function maybeUpload(group){let f=$('#f-imgFile')?.files?.[0];if(!f)return{};let dataUrl=await fileDataUrl(f);return await post('/api/admin/upload',{group,dataUrl,id:crypto.randomUUID()})}
function cardPayload(base={}){return{...base,title:$('#f-title').value,owner:$('#f-owner').value,cid:$('#f-cid').value,rar:$('#f-rar').value,p:Number($('#f-p').value),d:Number($('#f-d').value),s:Number($('#f-s').value),passive:Number($('#f-passive').value),tag:$('#f-tag').value,equipped:$('#f-equipped').value==='true',effect:$('#f-effect').value,crop:{x:50,y:50,z:1}}}
function enemyPayload(base={}){return{...base,enemyType:$('#f-enemyType').value,title:$('#f-title').value,cid:$('#f-cid').value,rar:$('#f-rar').value,p:Number($('#f-p').value),d:Number($('#f-d').value),s:Number($('#f-s').value),passive:Number($('#f-passive').value),weight:Number($('#f-weight').value),enabled:$('#f-enabled').value==='true',tag:$('#f-tag').value,effect:$('#f-effect').value,crop:{x:50,y:50,z:1}}}
async function saveUsers(){try{let rows=[...document.querySelectorAll('[data-user]')];for(let r of rows){let tokens={};r.querySelectorAll('[data-token]').forEach(i=>tokens[i.dataset.token]=Number(i.value));await post('/api/admin/user',{userId:r.dataset.user,cash:Number(r.querySelector('[data-cash]').value),tokens})}state.ok='User balances saved.';await load()}catch(e){state.err=e.message;render()}}
async function resetPin(id){if(!confirm(`Reset PIN for ${N[id]||id}?`))return;try{await post('/api/admin/user',{userId:id,resetPin:true});state.ok='PIN reset.';await load()}catch(e){state.err=e.message;render()}}
async function saveMarket(){try{let prices={};document.querySelectorAll('[data-market]').forEach(i=>prices[i.dataset.market]=Number(i.value));await post('/api/admin/market',{prices});state.ok='Market saved.';await load()}catch(e){state.err=e.message;render()}}
async function resetMarket(){if(!confirm('Reset all market prices to defaults?'))return;try{await post('/api/admin/market',{reset:true});state.ok='Market reset.';await load()}catch(e){state.err=e.message;render()}}
async function saveCard(){let c=state.modal.card;try{let upload=await maybeUpload('player-card');let payload=cardPayload({id:c.id,img:upload.url||c.img||null,imageKey:upload.key||c.imageKey||null});await post('/api/admin/card',payload);state.modal=null;state.ok='Card saved.';await load()}catch(e){state.err=e.message;render()}}
async function createCard(){try{let upload=await maybeUpload('player-card');let payload=cardPayload({img:upload.url||null,imageKey:upload.key||null});await post('/api/admin/card-create',payload);state.modal=null;state.ok='Card created.';await load()}catch(e){state.err=e.message;render()}}
async function deleteCard(){let c=state.modal.card;try{await post('/api/admin/card-delete',{id:c.id});state.modal=null;state.ok='Card permanently deleted.';await load()}catch(e){state.err=e.message;render()}}
async function saveEnemy(){let e=state.modal.enemy||{};try{let upload=await maybeUpload('enemy-template');let payload=enemyPayload({id:e.id,img:upload.url||e.img||null,imageKey:upload.key||e.imageKey||null});await post('/api/admin/enemy-template',payload);state.modal=null;state.ok='Enemy template saved.';await load()}catch(err){state.err=err.message;render()}}
async function deleteEnemy(){let e=state.modal.enemy;try{await post('/api/admin/enemy-template',{action:'delete',id:e.id});state.modal=null;state.ok='Enemy template deleted.';await load()}catch(err){state.err=err.message;render()}}
init();
(function(){if(document.getElementById('adminPrestigePatch'))return;let s=document.createElement('script');s.id='adminPrestigePatch';s.src='/admin/prestige.js?v=1';document.body.appendChild(s)})();