function installPrestigeCurrentCopy(){
  if(window.__ctcgPrestigeCurrentCopyInstalled)return;
  if(typeof prestige!=='function'){setTimeout(installPrestigeCurrentCopy,40);return}
  window.__ctcgPrestigeCurrentCopyInstalled=true;
  prestige=function(){
    const rows=(state.data&&state.data.prestige)||[];
    const totalXp=rows.reduce((s,r)=>s+Number(r.recentXp24h||0),0),activeOwners=rows.reduce((s,r)=>s+Number(r.activeOwners||0),0),anchors=rows.filter(r=>r.anchorPreview);
    return`<div class="head"><h1>Prestige</h1><p>Live character fundamentals used by the token market. Prestige helps set each token's market anchor, and prices drift around that anchor over time.</p></div><div class="cards"><div class="stat"><span>Top Prestige</span><b>${esc(rows[0]?.name||'None')}</b></div><div class="stat"><span>24h Card XP</span><b>${money(totalXp)}</b></div><div class="stat"><span>Active Owners</span><b>${money(activeOwners)}</b></div><div class="stat"><span>Live Anchors</span><b>${anchors.length?'Active':'No Data'}</b></div></div><section class="panel"><div class="panelTop"><h2>Character Prestige Scores</h2><p class="pill">Live market input</p></div><div class="prestigeGrid">${rows.map(r=>`<article class="prestigeCard"><div class="prestigeHead"><div><h3>${esc(r.name)}</h3><small>${esc(r.id)}</small></div><b>${money(r.prestigeScore)}</b></div>${prestigeBar(r.prestigeScore)}<div class="prestigeStats"><div><small>Multiplier</small><b>${Number(r.multiplier||0).toFixed(2)}x</b></div><div><small>Market Anchor</small><b>$${Number(r.anchorPreview||0).toFixed(2)}</b></div><div><small>Current Price</small><b>$${Number(r.currentPrice||0).toFixed(2)}</b></div><div><small>24h XP</small><b>${money(r.recentXp24h)}</b></div><div><small>7d XP</small><b>${money(r.recentXp7d)}</b></div><div><small>Cards</small><b>${money(r.activeCards)}/${money(r.totalCards)}</b></div><div><small>Owners</small><b>${money(r.owners)}</b></div><div><small>Win Rate</small><b>${money(r.winRate)}%</b></div></div><h4>Top Cards</h4>${prestigeCardList(r.topCards)}</article>`).join('')}</div></section><section class="panel"><div class="panelTop"><h2>Formula Notes</h2></div><div style="padding:18px;display:grid;gap:10px"><p>Prestige combines top-card strength, recent XP, owner diversity, active card breadth, wins, and MVPs.</p><p>The Market Anchor is the token's current center of gravity: base price multiplied by the prestige multiplier.</p><p>The live market now uses this anchor during price drift. Prices can still move above or below the anchor because normal market movement continues, but prestige is part of the live pricing pressure.</p></div></section>`;
  };
  if(state&&state.data&&state.tab==='prestige')render();
}
installPrestigeCurrentCopy();
